version: '3.9'

services:  
    client:
        container_name: client-numer
        build: 
            context: .
            dockerfile: ./client/Dockerfile
        volumes: 
            - '.:/usr/src/app'
            - '/usr/src/app/node_modules'
        ports: 
            - '3000:3000'
        tty: true
    server:
        container_name: server-numer
        build: 
            context: .
            dockerfile: ./server/Dockerfile
        volumes: 
            - '.:/user/src/app'
            - '/usr/src/app/node_modules'
        ports: 
            - '5500:5500'
        tty: true