name: Docker

on:
  push: 
    branches: [ main ]
jobs:
  push_to_registry: 
    name: Push Numerical Docker Image to Github Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build the docker-compose 
        run: docker-compose up -d --build
      - name: Check running containers
        run: docker ps -a
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          file: ./client/Dockerfile
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: t6tg/client-numerical
          tag_with_ref: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
