name: Docker

on:
  push: 
    branches: [ main ]
jobs:
  push_to_registry: 
    name: Push Numerical Docker Image to Github Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker Build Client
        run: |
          docker build ./client -t t6tg/client-numerical:latest
