name: Docker

on:
  push: 
    branches: [ main ]
jobs:
  push_to_registry: 
    name: Push Numerical Docker Image to Github Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Docker Build Client
        run: |
          docker build ./client -t t6tg/client-numerical:latest
