name: deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version:  14.x
      - name: Install Dependency
        run: cd client && npm install
      - name: build
        run: cd client && npm run build
      - name: deploy
        run: cd client && npm run deploy
