name: Docker

on:
  push: 
    branches: [ main ]
jobs:
  push_to_registry: 
    name: Push Numerical Docker Image to Github Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build the docker-compose 
        run: docker-compose up -d --build
      - name: Check running containers
        run: docker ps -a
      - name: Publish Image
        uses: craftech-io/package-action@v3.1.0
        with:
          tags: latest
          access_token: ${{ secrets.GITHUB_TOKEN }}
